### PR TITLE
feat: implement event list page

### LINKED ISSUE #102: [Events] Implement Event overview page
- [x] implement https://www.eder-gmbh.de/newstermine/veranstaltungen/

Styles and a lot of elements can be taken form press release list.

### PR DESCRIPTION
**Pull request by mhaack**
Fix #102

Test URLs:
- Before: https://main--eder-group--hlxsites.hlx.page/newstermine/veranstaltungen
- After: https://event-list--eder-group--hlxsites.hlx.page/newstermine/veranstaltungen

### CODE REVIEW

**Comment by alexcarol** [comment]
Full screen:
- Original font size is a lot smaller in "full size" on the original site, both on the event title and description.
Mobile:
- font size is also smaller in the original site
- the "details" button is bigger.
- Title seems to have a stronger "font-weight"

**Comment by alexcarol** [comment]
A few pictures are not matching the original content (saw it in the last three, but there might be more)
Original:
image

Franklin:
image

**Comment by mhaack** [comment]
On the pictures see my comment on Slack, we still need to have the correct export from the old system. I only manually changed the top 3 images for better preview. Please ignore the wrong images.

**Comment by mhaack** [comment]
@alexcarol addressed the styling issues as well. All expect "font-weight". Actually "font-weight" is correct, but we have a general issue with the font families the "Roboto" font is missing. Will create a separate issue for that.

**Comment by asthabh23** [comment]
Few points to consider:
- The heading and button text for each row/item needs to be bold.
Expected:
Screenshot 2023-01-31 at 1 08 54 PM
Current:
Screenshot 2023-01-31 at 1 09 11 PM

- On shrinking window below 1150px, the images overflow the desired width:
Expected:
Screenshot 2023-01-31 at 1 13 27 PM

Current:
Screenshot 2023-01-31 at 1 12 59 PM

- Below 768px, the button width needs to be fixed (for mobile view, button width of 100% its fine)
Expected:
Screenshot 2023-01-31 at 1 15 15 PM
Current:
Screenshot 2023-01-31 at 1 15 38 PM

**Comment by mhaack** [comment]
@asthabh23 fixed the style issues

**Comment by asthabh23** [comment]
@mhaack In mobile view, button width has to be 100%
Current:
Screenshot 2023-01-31 at 4 20 49 PM

Expected:
Screenshot 2023-01-31 at 4 21 30 PM

Also, PSI score is a bit low, possibly that needs to be checked

**Review by asthabh23 — APPROVED** [review]

**Pull request merged**
