### PR TITLE
Events: home page

### LINKED ISSUE #103: [Events] Implement Event list for homepage
Implement the event list showing lates events on the homepage.

### PR DESCRIPTION
**Pull request by hannessolo**
Fix #103 

Events block changed to add "compact" view.

Test URLs:
- Before: https://main--eder-group--hlxsites.hlx.page
- After: https://events-compact--eder-group--hlxsites.hlx.page
- Before: https://main--eder-group--hlxsites.hlx.page/newstermine/veranstaltungen
- After: https://events-compact--eder-group--hlxsites.hlx.page/newstermine/veranstaltungen

### CODE REVIEW

**Comment by hannessolo** [comment]
TODO: Add event type icon

**Comment by hannessolo** [comment]
After merging, replace home page content with /drafts/hhertach/index

**Comment by mhaack** [comment]
Screenshot 2023-01-31 at 18 02 32
I know this is also little off on the original but I think both lists should have same font size/style for heading and date and the icon should be place similar as well (either next to date or next to title)

**Comment by hannessolo** [comment]
Ok, I can do that tomorrow, if we aren't going for 100% match.

**Review by mhaack — APPROVED** [review]

**Pull request merged**
