### PR TITLE
Herovideo

### LINKED ISSUE #10: [Homepage] Implement Hero (Video) Block
Implement hero block used for https://www.eder-gmbh.de/

- [ ] auto play video for desktop
- [ ] image for mobile
- [ ] headline & logo overlay
- [ ] scroll down functionality

### PR DESCRIPTION
**Pull request by steinkopffp**
Fix #10

Test URLs:
- Before: https://main--eder-group--hlxsites.hlx.page/drafts/psteinkopff/
- After: https://herovideo--eder-group--hlxsites.hlx.page/drafts/psteinkopff/

### CODE REVIEW

**Comment by mhaack** [comment]
Desktop view works for me but on mobile the image is missing.

**Review by mhaack — APPROVED** [review]

**Review by asthabh23 — CHANGES_REQUESTED** [review]
Video seems fine for desktop view, but for media query below 768px (when it needs to be converted to image), the number of images increases as I shrink the browser window. This needs to be fixed.

screenshot for reference:
Screenshot 2023-01-20 at 5 05 17 PM

**Review by asthabh23 — CHANGES_REQUESTED** [review]
Few points to consider and would require a fix:
- The video is visible only after 992px on original site, but in our implementation it is visible starting 768px itself. 
- Below 768px, the height of image reduces to ~200px (as on original site). Possibly this also needs to be checked in current implementation

**Comment by asthabh23** [comment]
For the above mentioned suggestions, second point still needs a fix.
For reference:
At 700px, the hero image 
- on original site:
Screenshot 2023-01-25 at 7 45 47 PM

- on Franklin site:
Screenshot 2023-01-25 at 7 46 47 PM

The width of the image needs to be reduced basically. Rest seems great!

**Comment by alexcarol** [comment]
The headline looks broken in fullscreen:
image

**Comment by asthabh23** [comment]
@steinkopffp Your last commit seems to have broken the headline on the herovideo.
Also, the change for suggestion to reduce height of image below 768px can be done in CSS itself.
Possibly, you need to relook into last commit changes and revert them to fix the broken part.

**Comment by alexcarol** [comment]
What's this "dummy1" image that appears on the first frame of the video?

**Comment by mhaack** [comment]
"dummy1" image ist just Philipps test page, check on the home page url

**Comment by asthabh23** [comment]
on hero video:
```
heading is in uppercase (original site doesnt have entire heading in uppercase)
heading is breaking into 3 lines below 1222px (should be two lines)
Heading font size seems a bit larger
```
hero image:
```
image height is approx 200px below 768px (this needs to be fixed - screenshot in comments above)
between 768px-992px height of image is same as height of video (which is fine)
```

**Comment by mhaack** [comment]
@asthabh23 fixed the issues you mentioned above, all except `Heading font size seems a bit larger`. The font size, weight are identical but our fonts are wrong, created #114

**Comment by asthabh23** [comment]
Thanks @mhaack for the fixes. I just see padding introduced around hero video/picture which needs to be removed.

Screenshot for reference:
Screenshot 2023-01-30 at 2 24 53 PM

**Comment by mhaack** [comment]
@asthabh23 fixed style issue, please recheck.

**Comment by asthabh23** [comment]
looks good now, thanks for the fixes @mhaack

**Review by asthabh23 — APPROVED** [review]

**Pull request merged**
