### PR TITLE
Implement lightbox

### LINKED ISSUE #47: [Press Releases] Implement image lightbox
Implement the image lightbox block used on some news items. Samples:

- https://www.eder-gmbh.de/newstermine/pressemeldungen/detail/hyster-bringt-einen-neuen-gabelhochhubwagen-s20-auf-den-markt/
- https://www.eder-gmbh.de/newstermine/pressemeldungen/detail/eder-fahrzeugbau-erkundet/

### PR DESCRIPTION
**Pull request by alexcarol**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #47

Test URLs:
- Original: https://www.eder-gmbh.de/newstermine/pressemeldungen/detail/hyster-bringt-einen-neuen-gabelhochhubwagen-auf-den-markt
- Before: https://main--eder-group--hlxsites.hlx.page/newstermine/pressemeldungen/detail/hyster-bringt-einen-neuen-gabelhochhubwagen-auf-den-markt
- After: https://issue-47--eder-group--hlxsites.hlx.page/newstermine/pressemeldungen/detail/hyster-bringt-einen-neuen-gabelhochhubwagen-auf-den-markt

Notes:
- The original site allows for the website to be scrolled after the lightbox appeared (moving the lightbox too), on the new implementation the lightbox stays in a fixed position until it's dismissed.
- The original site doesn't seem to have a clear standard for the "article" vs "lightbox" image, so I've tried to find a value that works for a few of the articles, but it might need tweaks or potentially some sort of parameterization of the block.

### CODE REVIEW

**Review by asthabh23 — COMMENTED** [review]
Few points to consider: 
- The fade-in effect of lighthouse can be same as fade-out effect to give smooth transition look.
- The page is scrollable with lighthouse position fixed (when it appears), possibly that still requires a fix

**Comment by alexcarol** [comment]
> Few points to consider:
> 
> * The fade-in effect of lighthouse can be same as fade-out effect to give smooth transition look.
What do you mean here? It already fades in and out.
> * The page is scrollable with lighthouse position fixed (when it appears), possibly that still requires a fix
The original page allows scrolling of the whole page (even the lighthouse). I feel like the current behaviour is an improvement over it, do you agree @asthabh23 @mhaack? we could also work on preventing scroll completely, do you think that'd be something desirable? (not sure how much leeway we have here).

**Comment by asthabh23** [comment]
> The fade-in effect of lighthouse can be same as fade-out effect to give smooth transition look.
What do you mean here? It already fades in and out.
_For me, the fade-out effect is smooth (on closing the popped up picture) but when the picture pops up on initial click, the transition isn't smooth._ 

> The page is scrollable with lighthouse position fixed (when it appears), possibly that still requires a fix
The original page allows scrolling of the whole page (even the lighthouse). I feel like the current behaviour is an improvement over it, do you agree @asthabh23 @mhaack? we could also work on preventing scroll completely, do you think that'd be something desirable? (not sure how much leeway we have here).
The current one still looks fine, but I am not sure completely.. will let @mhaack answer this.

**Comment by mhaack** [comment]
On the scrolling ... if easy and not much effort lets fix it. Seems wrong to me if you can scroll while the lightbox view is open.

**Comment by mhaack** [comment]
@alexcarol can you please merge main into the branch, this will help to preview in the final news layout.

**Comment by alexcarol** [comment]
> @alexcarol can you please merge main into the branch, this will help to preview in the final news layout.

It is already merged, I tried reloading the file but it still looks wrong, I think this might be a franklin issue. Is there any way to debug it?

**Review by asthabh23 — APPROVED** [review]

**Pull request merged**
