### PR TITLE
Implement Press Relase / News overview

### LINKED ISSUE #18: [Press Releases] implement press release overview page
See https://www.eder-gmbh.de/newstermine/pressemeldungen/

- [ ] everything is one block
- [ ] filter press releases by meta data
- [ ] display result list
- [ ] support for pagination

This is blocked by #15 & #16

### PR DESCRIPTION
**Pull request by mhaack**
Fix #18

Test URLs:
- Before: https://main--eder-group--hlxsites.hlx.page/newstermine/pressemeldungen
- After: https://pressrelease-overview--eder-group--hlxsites.hlx.page/newstermine/pressemeldungen

### CODE REVIEW

**Comment by alexcarol** [comment]
There's a "standort" 0, is this an import issue?
image

**Comment by alexcarol** [comment]
The original website also has a custom selector design, whereas your version has the default one. Are you planning on working on it in a future iteration, or is that something that we're planning will be "lost"?

**Comment by alexcarol** [comment]
As another note, the existing website only shows the top "N" filters, and then forces you to scroll, is this something we might want for the franklin version?

**Comment by mhaack** [comment]
> There's a "standort" 0, is this an import issue?
This is a content issue, some docs imported seem to have no location set. Will fix that.

**Comment by mhaack** [comment]
> There's a "standort" 0, is this an import issue?

This is a content issue, some docs imported seem to have no location set. Will fix that.

> The original website also has a custom selector design, whereas your version has the default one. Are you planning on working on it in a future iteration, or is that something that we're planning will be "lost"?

I simplified this and replaced the custom div base select with standard select elements. This is also better for accessibility. If really requiered we can implement custom select boxes later.

> As another note, the existing website only shows the top "N" filters, and then forces you to scroll, is this something we might want for the franklin version?

Can this be done with standard select tag?

**Comment by alexcarol** [comment]
> > As another note, the existing website only shows the top "N" filters, and then forces you to scroll, is this something we might want for the franklin version?
> 
> Can this be done with standard select tag?

There's a "size" attribute that determines how many elements to show at once, haven't used it, but it should do the job.

**Comment by mhaack** [comment]
Size controls the entries directly visible, not in dropdown https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_size

**Pull request merged**
